In [1]:
import torch
from components.layers import InputEmbeddingLayer,PositionalEncodingLayer,LayerNormalizationLayer
from components.blocks import ResidualBlock, MultiHeadAttentionBlock, FeedForwardBlock
from models.blocks import EncoderBlock

In [2]:
model_dimension = 8
num_heads = 4
sequence_length = 3
dropout_rate = 0.1
vocab_size = 10000
batch_size = 2
features = 1

In [3]:
input_tensor = torch.randint(0, vocab_size, (batch_size, sequence_length))
input_tensor

tensor([[8971, 7504,   80],
        [7841, 4771, 9184]])

In [4]:
input_embedding_layer = InputEmbeddingLayer(model_dimension,vocab_size)
input_embedding_layer_output = input_embedding_layer(input_tensor)
input_embedding_layer_output

tensor([[[-1.5317,  1.6170,  0.9382, -1.4644, -3.2935,  0.5678, -0.5085,
           1.5592],
         [-2.5733, -3.5791,  2.7388,  1.5280, -0.4437, -4.8860, -4.5439,
          -0.5862],
         [ 1.5455, -5.8299, -5.1195, -1.9280,  4.1834,  2.9487,  1.1462,
           1.4685]],

        [[-3.8306, -1.0888, -1.1763, -1.6814, -6.4480, -4.5212, -1.4485,
          -0.4964],
         [ 4.0643, -3.8461,  1.1578,  2.1855, -2.1287, -6.6000,  8.3749,
           1.4199],
         [-3.1706,  4.2754,  1.0337, -0.1314,  0.7583,  0.5872,  5.2470,
           1.0315]]], grad_fn=<MulBackward0>)

In [5]:
input_embedding_layer_output.size()

torch.Size([2, 3, 8])

In [6]:
positional_encoding_layer = PositionalEncodingLayer(model_dimension, sequence_length, dropout_rate)
positional_encoding_layer_output = positional_encoding_layer(input_embedding_layer_output)
positional_encoding_layer_output


tensor([[[-1.7019,  2.9078,  0.0000, -0.5160, -3.6595,  1.7420, -0.5650,
           2.8435],
         [-1.9242, -3.3765,  3.1540,  2.8033, -0.4819, -4.3178, -5.0477,
           0.4597],
         [ 0.0000, -0.0000, -5.4676, -1.0533,  4.6705,  4.3873,  1.2758,
           2.7427]],

        [[-0.0000, -0.0986, -1.3070, -0.7572, -0.0000, -3.9125, -1.6095,
           0.0000],
         [ 0.0000, -3.6731,  1.3974,  3.5339, -2.3541, -6.2223,  9.3066,
           2.6888],
         [-2.5125,  4.2881,  1.3693,  0.9429,  0.8647,  1.7633,  0.0000,
           0.0000]]], grad_fn=<MulBackward0>)

In [7]:
mhab = MultiHeadAttentionBlock(model_dimension,num_heads,dropout_rate)


In [8]:
rbs = [ResidualBlock(features,dropout_rate),ResidualBlock(features,dropout_rate)]


In [9]:
lns = [LayerNormalizationLayer(features,10**(-6)),
       LayerNormalizationLayer(features,10**(-6))]

In [10]:
ffb = FeedForwardBlock(model_dimension,
                       100,
                       dropout_rate)

In [11]:
eb= EncoderBlock(mhab, ffb, rbs, lns)

In [12]:
eb(positional_encoding_layer_output,None)

tensor([[[-0.6176,  0.7960, -0.1014,  0.0548, -1.7403,  0.6858, -0.5502,
           1.4731],
         [-0.2151, -0.5907,  1.2849,  1.3928,  0.4261, -1.1185, -1.2552,
           0.0757],
         [-0.3106, -0.4211, -1.7776, -0.3636,  1.2568,  1.2728, -0.1249,
           0.4682]],

        [[ 0.8003,  0.5285, -0.1961,  0.1286,  0.7516, -2.1915, -0.4771,
           0.6557],
         [ 0.1507, -0.9010,  0.2425,  0.7832, -0.3771, -1.7419,  1.4774,
           0.3662],
         [-1.6815,  1.8600,  0.2987,  0.1886, -0.1449,  0.1917, -0.7282,
           0.0156]]], grad_fn=<AddBackward0>)